name: Run Maven Build

on:
  repository_dispatch:
    types: [sync_proto]

jobs:
  builds:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Checkout Source Repository
      uses: actions/checkout@v2
      with:
        repository: kylinVD0623/sync-proto-go
        token: ${{ secrets.TARGET_REPO_ACCESS_TOKEN }}
        path: sync-proto-go

    - name: Sync Protobuf Files
      run: |
        rsync -avz --delete sync-proto-go/grpc/cloud/ src/main/proto/grpc/cloud/

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with: 
        java-version: '11'
        distribution: 'adopt'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build with Maven
      run: mvn clean install

    - name: Commit and Push Changes
      env:
        SYNC_BRANCH_NAME: config/auto-sync-proto
        GH_TOKEN: ${{ secrets.TARGET_REPO_ACCESS_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git checkout -b ${SYNC_BRANCH_NAME}
        git add .
        git commit -m "Sync Proto files from github-actions-test" || true # Don't fail if nothing to commit
        git push --set-upstream origin HEAD:${SYNC_BRANCH_NAME}
        gh pr create --title "Sync .proto files" --body "This Pull Request updates the .proto files from github-actions-test" --repo kylinVD0623/sync-proto-java --base main --head ${SYNC_BRANCH_NAME} || true # Don't fail if nothing to commit