name: Run Maven Build

on:
  repository_dispatch:
    types: [sync_proto]

jobs:
  builds:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Target Repository
      uses: actions/checkout@v2

    - name: Checkout Source Repository
      uses: actions/checkout@v2
      with:
        repository: kylinVD0623/sync-proto-go
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        path: sync-proto-go

    - name: Config Git
      env:
        SYNC_BRANCH_NAME: config/auto-sync-proto
      run: |
        git config --global user.name "Github Actions"
        git config --global user.email "actions@github.com"
        git checkout -b ${SYNC_BRANCH_NAME}

    - name: Sync Protobuf Files
      run: |
        rsync -av --delete --include='*.proto' --exclude='*' sync-proto-go/grpc/cloud/ src/main/proto/grpc/cloud/

    # - name: Set up JDK 11
    #   uses: actions/setup-java@v2
    #   with: 
    #     java-version: '11'
    #     distribution: 'adopt'

    # - name: Cache Maven packages
    #   uses: actions/cache@v2
    #   with:
    #     path: ~/.m2
    #     key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
    #     restore-keys: ${{ runner.os }}-m2

    # - name: Build with Maven
    #   run: mvn clean install

    - name: Commit and Push Changes
      env:
        SYNC_BRANCH_NAME: config/auto-sync-proto
        GH_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
      run: |
        git add .
        git commit -m "Sync Proto Files from Github Actions" || true # Don't fail if nothing to commit
        git push --set-upstream origin HEAD:${SYNC_BRANCH_NAME}

    # - name: Create Pull Request
    #   uses: peter-evans/create-pull-request@v3
    #   with:
    #     token: ${{ secrets.REPO_ACCESS_TOKEN }}
    #     commit-message: "Sync Proto Files from Github Actions"
    #     title: "Sync Proto Files from Github Actions"
    #     body: "This pull request updates proto files from sync-proto-go"
    #     branch: "config/auto-sync-proto"
    #     base: "main"
        